import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {mergeGeometries} from './vendor/BufferGeometryUtils.js';
import {createForklift,V} from './model.js';
import {createWarehouse} from './world.js';
import {Simulation,SETTINGS,SPEED_MODES,clamp,fitsSlot,loadOffset} from './physics.js';
import {ForkliftSound} from './sound.js';
import {StorageTimer,formatTime} from './timer.js';
import {cargoSize,cargoName} from './cargo.js';

const $=s=>document.querySelector(s),canvas=$('#scene'),mobile=matchMedia('(pointer:coarse)').matches;
let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});}catch(e){$('#loading').innerHTML='<strong>O 3D não pôde iniciar neste navegador.</strong><span>Ative a aceleração gráfica ou abra em um navegador com WebGL 2.</span><button onclick="location.reload()">Tentar novamente</button>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.5:1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;
const scene=new T.Scene();scene.background=new T.Color('#abb9bf');scene.fog=new T.Fog('#abb9bf',25,60);
const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.035,80);const ambient=new T.HemisphereLight('#eff8ff','#697374',2.1);scene.add(ambient);
const keyLight=new T.DirectionalLight('#fff2dc',3.5);keyLight.position.set(-8,13,-5);keyLight.castShadow=true;keyLight.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);Object.assign(keyLight.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:.1,far:40});keyLight.shadow.bias=-.00015;keyLight.shadow.normalBias=.019;scene.add(keyLight,keyLight.target);
const fill=new T.DirectionalLight('#d4e8fa',1.15);fill.position.set(9,8,5);scene.add(fill);

// A neutral procedural studio environment supplies broad, physically based paint reflections.
const envScene=new T.Scene();envScene.background=new T.Color('#939fa5');for(const [x,y,z,w,h,intensity] of [[0,8,0,10,8,3],[-7,3,0,5,8,2],[7,4,-4,4,5,1.8],[0,3,8,9,3,2]]){const panel=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({color:new T.Color(intensity,intensity,intensity),side:T.DoubleSide}));panel.position.set(x,y,z);panel.lookAt(0,1,0);envScene.add(panel);}
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(envScene,.04,.1,30).texture;scene.environmentIntensity=.43;pmrem.dispose();
const truck=createForklift();scene.add(truck.root);const world=createWarehouse(scene,mobile);const sim=new Simulation(world.obstacles,world.pallets,world.slots);

// Batch only immutable geometry. Moving controls, tyres, carriage and telescopic rails remain independent.
function batchStatic(group,exclude=new Set()){
 group.updateWorldMatrix(true,true);const inverse=group.matrixWorld.clone().invert(),batches=new Map(),remove=[];
 function walk(o){if(o!==group&&exclude.has(o))return;if(o.isMesh&&!o.isInstancedMesh&&!Array.isArray(o.material)&&o!==group){const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(new T.Matrix4().multiplyMatrices(inverse,o.matrixWorld));if(!g.getAttribute('uv'))g.setAttribute('uv',new T.Float32BufferAttribute(new Float32Array(g.getAttribute('position').count*2),2));for(let name of Object.keys(g.attributes))if(!['position','normal','uv'].includes(name))g.deleteAttribute(name);let b=batches.get(o.material);if(!b){b=[];batches.set(o.material,b);}b.push(g);remove.push(o);}for(const child of o.children)walk(child);}
 walk(group);for(let [material,geometries]of batches){let geometry=mergeGeometries(geometries,false);if(!geometry)continue;const m=new T.Mesh(geometry,material);m.castShadow=!material.transparent;m.receiveShadow=true;group.add(m);for(let g of geometries)g.dispose();}for(let m of remove)m.removeFromParent();
}
const wheelSpins=[...truck.fronts,...truck.rear].map(w=>w.spin);const moving=[truck.body,truck.steeringAxle,truck.steeringWheel,...truck.joysticks,...truck.pedals,truck.carriage,truck.inner,truck.piston,...truck.chainLinks,...wheelSpins];batchStatic(truck.root,new Set(moving));for(let g of moving)if(!g.isMesh)batchStatic(g,new Set(moving));batchStatic(world.root);world.palletMeshes.forEach(m=>batchStatic(m));world.slotMarkers.forEach(({marker})=>batchStatic(marker));
const exercise=new StorageTimer();

const headlight=new T.SpotLight('#fff0d4',0,10,.55,.55,1.4);headlight.position.set(0,1.9,.35);headlight.target.position.set(0,0,6);truck.root.add(headlight,headlight.target);let lightsOn=false;
const orbit=new OrbitControls(camera,canvas);orbit.enableDamping=true;orbit.dampingFactor=.085;orbit.enablePan=false;orbit.minDistance=1.6;orbit.maxDistance=10.5;orbit.minPolarAngle=.12;orbit.maxPolarAngle=1.70;orbit.rotateSpeed=.60;orbit.zoomSpeed=.8;orbit.enabled=false;orbit.touches={ONE:T.TOUCH.ROTATE,TWO:T.TOUCH.DOLLY_ROTATE};
let cameraMode='follow',cockpitYaw=0,cockpitPitch=-.28,lastOrbitTarget=new T.Vector3(),cameraInitialized=false;
const cameraHint={follow:'A câmera acompanha o equipamento',cab:'Arraste para olhar ao redor do cockpit',orbit:'Arraste para girar · role ou pince para aproximar'};
function selectCamera(mode){cameraMode=mode;orbit.enabled=mode==='orbit';cameraInitialized=false;document.querySelectorAll('[data-camera]').forEach(b=>{const active=b.dataset.camera===mode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('#camera-hint').textContent=cameraHint[mode];if(mode==='cab'){cockpitYaw=0;cockpitPitch=-.28;}if(mode==='orbit'){const s=sim.state;const t=V(s.x,.95,s.z+.3);camera.position.copy(V(3.6,2.8,-4.2).applyAxisAngle(V(0,1,0),s.yaw).add(V(s.x,0,s.z)));orbit.target.copy(t);lastOrbitTarget.copy(t);orbit.update();}canvas.focus({preventScroll:true});}
document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>selectCamera(b.dataset.camera)));
function updateCamera(dt){let s=sim.state;camera.aspect=innerWidth/innerHeight;
 if(cameraMode==='cab'){camera.fov=mobile&&innerWidth>innerHeight?84:78;camera.position.copy(V(.04,1.68,-.30).applyAxisAngle(V(0,1,0),s.yaw).add(V(s.x,0,s.z)));const yaw=s.yaw+cockpitYaw;camera.lookAt(camera.position.clone().add(V(Math.sin(yaw)*Math.cos(cockpitPitch),Math.sin(cockpitPitch),Math.cos(yaw)*Math.cos(cockpitPitch))));}
 else if(cameraMode==='follow'){camera.fov=mobile&&innerWidth<innerHeight?53:46;let liftView=Math.max(0,s.fork-.5),offset=V(3.5,(mobile&&innerWidth<innerHeight?3.0:2.65)+liftView*.32,-4.7).applyAxisAngle(V(0,1,0),s.yaw),desired=offset.add(V(s.x,0,s.z));desired.x=clamp(desired.x,-11.5,11.5);desired.z=clamp(desired.z,-15.4,15.4);if(!cameraInitialized)camera.position.copy(desired);else camera.position.lerp(desired,1-Math.exp(-dt*5.3));camera.lookAt(s.x,.97+liftView*.30,s.z+.24);}
 else{camera.fov=48;let target=V(s.x,.99,s.z+.30),delta=target.clone().sub(lastOrbitTarget);camera.position.add(delta);orbit.target.add(delta);lastOrbitTarget.copy(target);orbit.update();camera.position.y=clamp(camera.position.y,.18,6.50);camera.position.x=clamp(camera.position.x,-11.7,11.7);camera.position.z=clamp(camera.position.z,-15.6,15.6);camera.lookAt(orbit.target);}
 cameraInitialized=true;camera.updateProjectionMatrix();
}
// Cockpit free look. OrbitControls owns pointer gestures only in orbital mode.
let lookPointer=null,lookX=0,lookY=0;canvas.addEventListener('pointerdown',e=>{if(cameraMode!=='cab')return;lookPointer=e.pointerId;lookX=e.clientX;lookY=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(lookPointer!==e.pointerId||cameraMode!=='cab')return;cockpitYaw=clamp(cockpitYaw-(e.clientX-lookX)*.004,-1.8,1.8);cockpitPitch=clamp(cockpitPitch+(e.clientY-lookY)*.004,-1.15,.55);lookX=e.clientX;lookY=e.clientY;});for(let event of['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>lookPointer=null);

const sources=new Map();function updateInput(){sim.input={};for(let action of sources.values())sim.input[action]=true;if(sim.input.horn&&!sound.enabled)sound.setEnabled(true);$('#horn').classList.toggle('pressed',!!sim.input.horn);}
function clearInput(){sources.clear();updateInput();document.querySelectorAll('.pressed').forEach(e=>e.classList.remove('pressed'));lookPointer=null;}
for(let b of document.querySelectorAll('[data-hold]')){b.addEventListener('pointerdown',e=>{e.preventDefault();if($('#instructions').open)return;b.setPointerCapture(e.pointerId);sources.set('p'+e.pointerId,b.dataset.hold);b.classList.add('pressed');updateInput();});const end=e=>{sources.delete('p'+e.pointerId);b.classList.remove('pressed');updateInput();};for(let evt of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(evt,end);b.addEventListener('contextmenu',e=>e.preventDefault());}
const keyMap={ArrowUp:'forward',ArrowDown:'reverse',ArrowLeft:'left',ArrowRight:'right',Space:'lift',KeyR:'lift',PageUp:'lift',KeyF:'lower',PageDown:'lower',KeyH:'horn'};
function chooseSpeed(mode){if(!sim.setSpeedMode(mode))return;updateHud();toast(`Velocidade ${SPEED_MODES[mode].name}: até ${SPEED_MODES[mode].kmh} km/h. Garfos altos e carga reduzem o limite.`);canvas.focus({preventScroll:true});}
document.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>chooseSpeed(b.dataset.speed)));
addEventListener('keydown',e=>{if(help.open||e.repeat||e.target.closest?.('input,textarea,select,[contenteditable="true"]'))return;const mode={Digit1:'precision',Numpad1:'precision',Digit2:'normal',Numpad2:'normal',Digit3:'travel',Numpad3:'travel'}[e.code];if(mode){e.preventDefault();chooseSpeed(mode);}});
addEventListener('keydown',e=>{if($('#instructions').open)return;if(e.target.closest?.('input,textarea,select,[contenteditable="true"]'))return;let a=keyMap[e.code];if(a){e.preventDefault();sources.set(e.code,a);updateInput();return;}if(e.repeat)return;if(e.code==='Enter'&&e.target.closest?.('button'))return;if(e.code==='Enter'){e.preventDefault();toggleLoad();}if(e.code==='KeyC')selectCamera(cameraMode==='cab'?'follow':'cab');if(e.code==='KeyO'||e.code==='KeyI')selectCamera('orbit');if(e.code==='KeyL')toggleLights();});addEventListener('keyup',e=>{if(e.code==='Space'&&!e.target.closest?.('input,textarea,select,[contenteditable="true"]'))e.preventDefault();sources.delete(e.code);updateInput();});addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInput();});
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3100);}
function syncPallets(){for(let p of world.pallets){const m=world.palletMeshes[p.id];if(p.attached){if(m.parent!==truck.carriage){truck.carriage.add(m);m.position.set(0,-SETTINGS.supportOffset,loadOffset(p)-.909-.145);m.rotation.set(0,0,0);}}else{if(m.parent!==scene)scene.add(m);m.position.set(p.x,p.y||0,p.z);m.rotation.set(0,p.yaw,0);}}}
function toggleLoad(){let r=sim.toggleLoad();const slot=world.slots.find(slot=>slot.id===r.p?.slotId),completed=exercise.recordStorage(r,slot,performance.now());toast(completed?`CARGA GUARDADA EM ${formatTime(exercise.elapsed)}. Exercício concluído!`:r.message);if(!r.ok)return;updateTruck(0);updateHud();}
$('#pickup').addEventListener('click',()=>{toggleLoad();canvas.focus({preventScroll:true});});
function reset(silent=false){clearInput();world.pallets.forEach((p,i)=>Object.assign(p,world.initialPallets[i]));sim.reset();exercise.reset();syncPallets();cameraInitialized=false;selectCamera(cameraMode);if(!silent)toast('Equipamento e pallets reposicionados. Cronômetro zerado.');updateHud();}
$('#reset').addEventListener('click',()=>reset());
$('#timer-minutes').addEventListener('focus',clearInput);
$('#timer-minutes').addEventListener('input',()=>{if(exercise.setMinutes(Number($('#timer-minutes').value)))updateTimer();});
$('#timer-start').addEventListener('click',()=>{const input=$('#timer-minutes');if(!input.reportValidity())return;if(exercise.status!=='running'&&!exercise.setMinutes(Number(input.value)))return;reset(true);exercise.start(performance.now());updateTimer();toast('Cronômetro iniciado. Guarde uma carga em qualquer vaga livre.');canvas.focus({preventScroll:true});});
$('#timer-cancel').addEventListener('click',()=>{exercise.reset();clearInput();updateTimer();canvas.focus({preventScroll:true});});
function updateTimer(){const running=exercise.status==='running';$('#timer-panel').dataset.state=exercise.status;$('#timer-panel').classList.toggle('urgent',running&&exercise.remaining<=30);$('#timer-clock').textContent=formatTime(exercise.remaining,true);$('#timer-elapsed').textContent=formatTime(exercise.elapsed);$('#timer-minutes').disabled=running;$('#timer-start').textContent=exercise.status==='idle'?'Iniciar':'Recomeçar';$('#timer-cancel').hidden=!running;const label={idle:'Pronto para iniciar',running:'Guarde a carga no prazo',completed:'CARGA GUARDADA',expired:'TEMPO ESGOTADO'}[exercise.status];if($('#timer-result').textContent!==label)$('#timer-result').textContent=label;}
const help=$('#instructions');$('#help').addEventListener('click',()=>{clearInput();help.showModal();});function closeHelp(){help.close();canvas.focus({preventScroll:true});}$('#close-help').addEventListener('click',closeHelp);$('#start').addEventListener('click',closeHelp);help.addEventListener('click',e=>{if(e.target===help){const r=help.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeHelp();}});
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Use a opção de tela cheia do navegador.');}catch{toast('A tela cheia não está disponível neste navegador.');}});
function toggleLights(){lightsOn=!lightsOn;headlight.intensity=lightsOn?22:0;truck.lamps.forEach(m=>m.emissiveIntensity=lightsOn?3:.1);$('#lights').classList.toggle('on',lightsOn);$('#lights').setAttribute('aria-label',lightsOn?'Desligar faróis':'Ligar faróis');}$('#lights').addEventListener('click',toggleLights);

const sound=new ForkliftSound(refreshAudio);let soundActiveWindow=true;
function refreshAudio(){const ready=sound.context?.state==='running',on=sound.enabled;$('#audio').classList.toggle('on',on);$('#audio').setAttribute('aria-pressed',String(on));$('#audio').setAttribute('aria-label',on?'Desativar sons':'Ativar sons');$('#audio').title=on?'Desativar sons':'Ativar sons';$('#sound-state').textContent=sound.unavailable?'Áudio indisponível':!on?'Som desligado':ready?'Motor · hidráulica · alarme de ré':'Toque ou use o teclado para ouvir';}
$('#audio').addEventListener('click',()=>sound.setEnabled(!sound.enabled));
const unlockSound=e=>{if(!e.target.closest?.('#audio'))sound.unlock();};document.addEventListener('pointerdown',unlockSound,{capture:true});document.addEventListener('keydown',unlockSound,{capture:true});
addEventListener('blur',()=>{soundActiveWindow=false;sound.silence();});addEventListener('focus',()=>{soundActiveWindow=true;});document.addEventListener('visibilitychange',()=>{if(document.hidden)sound.silence();});
$('#horn').addEventListener('keydown',e=>{if(e.code==='Enter'&&!help.open){e.preventDefault();sources.set('hornButton','horn');updateInput();}});$('#horn').addEventListener('keyup',e=>{if(e.code==='Enter'){e.preventDefault();sources.delete('hornButton');updateInput();}});$('#horn').addEventListener('blur',()=>{sources.delete('hornButton');updateInput();});
$('#horn').addEventListener('click',e=>{if(e.detail===0&&!help.open){sound.unlock();sources.set('hornClick','horn');updateInput();setTimeout(()=>{sources.delete('hornClick');updateInput();},350);}});
function updateSound(){sound.update(sim,help.open||document.hidden||!soundActiveWindow);}
refreshAudio();

function updateHud(){let s=sim.state,n=sim.nearest(),loaded=!!s.loaded,ready=!!n?.ready,support=loaded?sim.support():null,target=loaded?sim.storageTarget():null;
 updateTimer();
 $('#speed-mode').textContent=SPEED_MODES[sim.speedMode].name;for(let b of document.querySelectorAll('[data-speed]')){const active=b.dataset.speed===sim.speedMode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));}
 $('#speed').textContent=(Math.abs(s.v)*3.6).toFixed(1).replace('.',',');$('#speed-bar').style.width=Math.min(100,Math.abs(s.v)/SETTINGS.maxForward*100)+'%';$('#gear').textContent=s.v>.02?'D':s.v<-.02?'R':'N';$('#height').textContent=s.fork.toFixed(2).replace('.',',');$('#load').textContent=loaded?'Pallet preso':'Sem carga';$('#load').style.color=loaded?'#fca56f':'';$('#limit').textContent=(sim.maxSpeed*3.6||8).toFixed(0);
 let alignment='Aproximar',title='Aproxime-se do pallet',detail='Mantenha os garfos baixos e entre pelos vãos.';
 if(loaded){alignment='Carga fixada';title='ESCOLHA UMA VAGA LIVRE PARA GUARDAR';detail='Marcas verdes: vagas livres. Respeite o espaço acima da carga.';if(support?.slot){alignment='Apoiado';title=`${support.slot.bay} · NÍVEL ${support.slot.level} — PRONTO PARA GUARDAR`;detail='Pare e acione SOLTAR. Depois recue com os garfos.';}else if(target&&target.d<3){const h=target.forkHeight.toFixed(2).replace('.',',');alignment=target.contained?'Sobre a vaga':'Alinhar à vaga';title=`${target.slot.bay} · NÍVEL ${target.slot.level} · GARFOS ${h} m`;detail=target.contained?'Desça devagar até apoiar a carga na prateleira.':s.fork<target.forkHeight+.015?`Suba um pouco acima de ${h} m antes de avançar.`:'Centralize a carga na marca verde e avance devagar.';}else if(support){detail='SUBIR eleva a carga. SOLTAR a deixa no piso.';}}
 else if(sim.withdrawalPending()){alignment='Garfos livres';title='CARGA SOLTA — RECUE EM LINHA RETA';detail='Os garfos estão livres. Saia do pallet antes de baixar ou virar.';}
 else if(ready){alignment='Alinhado';title='PALLET ALINHADO — SUBIR OU PEGAR';detail='Segure ESPAÇO ou SUBIR para elevar o material.';}
 else if(n&&n.d<1.25){if(n.relativeHeight>.064){alignment='Baixar garfos';detail='Desça os garfos até os vãos do pallet.';}else if(n.relativeHeight<.042){alignment='Subir garfos';detail=`Suba até ${(n.p.y+.05).toFixed(2).replace('.',',')} m para entrar nos vãos.`;}else if(Math.abs(s.v)>.16&&n.d<.3){alignment='Parar';detail='Pare para fixar o pallet.';}else if(Math.abs(n.local.x)>.065||n.angle>.075){alignment='Ajustar direção';detail='Centralize os dois garfos nos vãos do pallet.';}else{alignment='Avançar devagar';detail='Entre um pouco mais com os garfos.';}title='Ajuste a aproximação';}
 $('#alignment').textContent=alignment;$('#alignment').style.color=ready||support?.slot?'#85d9a0':'';$('#prompt-title').textContent=title;$('#prompt-detail').textContent=detail;$('.operation-prompt').classList.toggle('ready',ready||!!support?.slot);$('.operation-prompt').classList.toggle('loaded',loaded);$('#pickup').setAttribute('aria-label',loaded?'Soltar pallet':'Pegar pallet');$('#pickup').disabled=sim.withdrawalPending();$('#pickup-label').textContent=sim.withdrawalPending()?'GARFOS LIVRES':loaded?(support?.slot?'GUARDAR / SOLTAR':'SOLTAR'):'PEGAR';$('#hydraulic-status').textContent=sim.withdrawalPending()?'Garfos livres — recue primeiro':sim.forkBlocked?'Obstáculo — ajuste a posição':s.fork>=SETTINGS.maxFork-.001?'Altura máxima — 3,23 m':`${s.fork.toFixed(2).replace('.',',')} / 3,23 m`;
 for(let {slot,marker,material}of world.slotMarkers){marker.visible=!sim.slotOccupied(slot);const compatible=!loaded||fitsSlot(s.loaded,slot);material.color.set(compatible?(target?.slot.id===slot.id?'#fff18c':'#82cba0'):'#9a978a');material.opacity=compatible?.80:.22;}
 const product=s.loaded||(n?.d<1.4?n.p:null);$('#product-name').textContent=product?cargoName(product):'Escolha uma carga';if(product){const size=cargoSize(product);$('#product-size').textContent=`${size.width.toFixed(2)} × ${size.depth.toFixed(2)} × ${size.height.toFixed(2)} m`.replaceAll('.',',');}else $('#product-size').textContent='Caixas · tambores · sacarias · bobinas';$('#rack-vacancies').textContent=`${world.slots.filter(slot=>!sim.slotOccupied(slot)).length} / ${world.slots.length} vagas livres`;
 truck.updateDisplay(s.v,s.fork,loaded);
}
let oldSpeed=0;function updateTruck(dt){const s=sim.state;truck.root.position.set(s.x,0,s.z);truck.root.rotation.y=s.yaw;truck.carriage.position.y=s.fork-.09;let extension=Math.max(0,s.fork-1.42);truck.inner.position.y=extension;truck.piston.scale.y=1+extension;truck.piston.position.y=1.36+extension*.5;
 syncPallets();
 truck.steeringAxle.rotation.y=-s.steer;truck.steeringWheel.rotation.y=s.steer*3.5;for(let w of[...truck.fronts,...truck.rear])w.spin.rotation.x+=s.v*dt/w.r;
 truck.joysticks[0].rotation.x=T.MathUtils.damp(truck.joysticks[0].rotation.x,sim.input.lift?-.25:sim.input.lower?.25:0,14,dt);truck.joysticks[1].rotation.x=T.MathUtils.damp(truck.joysticks[1].rotation.x,0,14,dt);truck.pedals[1].rotation.x=T.MathUtils.damp(truck.pedals[1].rotation.x,(sim.input.forward||sim.input.reverse)?-.11:-.30,12,dt);truck.pedals[0].rotation.x=T.MathUtils.damp(truck.pedals[0].rotation.x,Math.abs(s.v)<Math.abs(oldSpeed)-.001?-.10:-.30,12,dt);
 let acceleration=(s.v-oldSpeed)/Math.max(.01,dt);truck.body.rotation.x=T.MathUtils.damp(truck.body.rotation.x,clamp(-acceleration*.0015,-.008,.008),9,dt);oldSpeed=s.v;truck.beaconMat.emissiveIntensity=.45+Math.pow(Math.max(0,Math.sin(sim.time*6)),8)*2;for(let chain of truck.chainLinks)chain.scale.y=1+extension*.50;
 keyLight.target.position.set(s.x,0,s.z);keyLight.position.set(s.x-4,6.3,s.z-2);
}
const clock=new T.Clock();let hudAccum=1,frameCount=0,qualityTime=0,totalFrameTime=0,autoOptimized=false;
function frame(){requestAnimationFrame(frame);let dt=Math.min(clock.getDelta(),.04);if(exercise.tick(performance.now())==='expired'){toast('TEMPO ESGOTADO. Use Recomeçar para tentar novamente.');updateTimer();}if(!help.open&&!document.hidden&&soundActiveWindow){let hit=sim.step(dt);if(hit){const msg=hit.type==='pickup'?hit.message:hit.kind==='hydraulic'?'Os garfos ou a carga tocaram a estrutura. Ajuste a altura antes de avançar.':hit.kind==='fork'?'Os garfos tocaram no pallet. Ajuste a altura e o alinhamento.':'Barreira de aproximação. Pare e ajuste a manobra.';toast(msg);if(hit.type==='collision'&&mobile&&navigator.vibrate)navigator.vibrate([35,20,25]);}}
 updateTruck(dt);updateCamera(dt);updateSound();hudAccum+=dt;if(hudAccum>.10){updateHud();hudAccum=0;}renderer.render(scene,camera);
 if(!autoOptimized&&frameCount<200){frameCount++;totalFrameTime+=dt;if(frameCount===200&&totalFrameTime/200>.032){renderer.setPixelRatio(mobile?1:1.25);autoOptimized=true;}}
}
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();cameraInitialized=false;});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();clearInput();toast('A renderização foi interrompida. Recarregue para retomar o simulador.');});
updateTruck(0);selectCamera('follow');updateCamera(0);updateHud();renderer.compile(scene,camera);$('#loading').remove();frame();
